language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "SogolHaghighat"
    token:
      secure: "YEcx3wNvggwlJlV4OaitkauOkSWt6nQbOKNJ9286I6Mys5FzpXCBatLHUuBDiZa33rRWm/2OpPLVx8jtpRsxkB6lGQtpAafFPc60rlkcOFn75hIi8B+z4sdA1IuTVIIeXLjjSS83I/Vd1xqgKSJYHfsp4slT5O1CiC/qKhtTKMG9NmyPF4sMopjYZy5JqmAJS01A15JaHmzTjHAJFXE/qRDY7nEmg/MjOS4PIz1IQqa9KW1uL8qmGoH9ZJCYK2KhRTaq/qERBo24ijk6bd1uDws4fcha+DtftiB+eZLuNxBHVg7n+AZEzNhqMIbF/u6mJdS4Adl5Inp9R7MqP8Lsma+dgB06ZOEkWl+yUZuOO+Rp2C33OJIXM7mVA3/b8wAow1qKnk3xk5F9TITGSt1jA+SMSKOTr+ux9bKmCudsC2IhuXFExrXHvGXBAk6rIYWu91cgoAHuFrBQ7CnLsgM9lJ6cZ6d/Uzdy7LuyejB+1pxwljTC4yy7yIwnIqDP02xd6YbARF0a08jI88YoqVhsPyHtQqJ+efGfWNremcDDD5bfLSqSbl2oEwEyGsbeRP9+fpp06TcR5LijIXJIWIn6MBfuirRCEDDSKY/OJOie9ezoZKXAIEfsjZTHaWxNrwTaSaB4+N6gw4IzQblGPJZDdDTHKGzYGLqMvGmaZ4QGJeE="

jdk:
    - openjdk8

script:
    - ./gradlew sonarqube
group: stable
dist: trusty
os: linux
