language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "tmetzl-github"
    token:
      secure: "mZsxIRpwf6c5DXBdT3bAf+/enbopLtwdn+YNZBIY2/odQdFNfv+rJCDewQiUyehDlpLvyKXgidwvmd1RaOCA4BBFZitdhhYx/7HzEOavMWl7cNg52STiktQbm0kTIxAbgrA9TaYaxD5FkuJ1tG6k7Ex9m/lRO1Gob3TQEEjj2F/v3VP7mWOH5stoTOJJFc0nWE1MM/dKKITzdk+gB/vHaIk1OaxwmOA8Hf+WmhK3ojcRjWuokYbih5mJiMNxHpElIt2J4c/t4pv3Z4ODLABvWsBfl64Jjr71UHN1mKBV9CSMShpFyExkGAvb3emJnX+enTjrBFpVjD9Uy/vACDoLA00O31LxkZNm6omPUlfs85b03xMTvF5q+Q0EAhw7IYJVhTWswxVS+pjk2tMftrPW+YQ2naIZuDV4kdpCfFke6t4Z0ZzSMbzH7sULYMPeKwtl7Jrh2zaklEvriBmK2ufulrVxuVMs239qyIZE8vF1IZF6CsKHvI1o1/pEmq7XCPZAcFMkHnlLU/j2zX5xb1S26DHG/AxuNODO5PvUxT19MB5aqnFS5KMvMwl9fv9hG7DlS78AnrNIEno9LRrLjxdsINIQju5kl8wDNQxaIGZwLax62Z1aODoIzlDGrvO1avMjqtLNqZX4n0dKNy9prDVPdBigE2ZSDqV+T9mTjXVZqbU="
    branches:
      - SonarCloud-Feature

jdk:
    - openjdk8

script:
    - ./gradlew sonarqube
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
        - '$HOME/.gradle'
        - '$.gradle'

group: stable
dist: trusty
os: linux
