language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "HBRS-MAAS/project-pieceofcake"
    token:
      secure: "JfgE7DPqmrbOZ8PEhRwj7UVdNnAjY9Mxj06M/Hue12DWqlIAjjRwJm9qe8dBn3YCk28eGmgqt6ugXB/BS0pdGwafJGOt3k35KosQB1kw6yxydPt08MfBAcJsUDGpRPwvznW2/moNfa8O8kLsYwTPariIUmCLOq73KREydLndsHV25i8wf5ffLfEfATrcdjiBvIJF89l8Dw2CiniCbrd78ryr37a9pz+o0cTmPPNNrcU4IjnRCN6FWN233QnIBWxhjEqRNs75oA0nCm8hIXEu3zf4/mXVkP82v62SQRTGpizi1Cn1SApW5b0r6i+e2NroDsYtr8kF9p0vMN03L+K0Egsnj2O/4gEWu7JVO12YMh2IGyyiE8GqSx4LAfvE8QCjAepB41FrcGVHfLHRf3zR7rMXyNcSbsnvNllxmfG/O4WwHZigL/K8PM8QkdJvXNojhJ7tyOX+HpHUC22ncd2PN4rd6Ib4SwdSWxa+4kfwKsvsttOq4RwSS8QOo7wtCMSCIbVK6bto+vF0j2AkjTNh6HpLfwJQhHlLp4ldx0HrZmyE78wxv8D72mDXRJoOD2SQFl6hH2eWlAIaFBGOX1hTexW7Zotn5x2eW8m4vfxg31MZZKKdnrksExS6Mey4mOQkstncEz/j3T2K3774a5aNfVC4LItgiuogTv3UU3lnSBA="
    branches:
      - SonarCloud-Feature

jdk:
    - openjdk8

script:
    - ./gradlew sonarqube
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
        - '$HOME/.gradle'
        - '$.gradle'

group: stable
dist: trusty
os: linux
